#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Routing test with default controller

# hello_page:
#     path: /hello
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#     defaults:
#       template: 'pages/hello_page.html.twig'
